# Google Cloud Build Configuration
# Automates building and deploying to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/karyakarta-agent:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/karyakarta-agent:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/karyakarta-agent:$COMMIT_SHA'
    id: 'push-image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'karyakarta-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/karyakarta-agent:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      # Environment variables (set these in Cloud Build or Secret Manager)
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--update-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest,SERPER_API_KEY=serper-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_KEY=supabase-key:latest'
    id: 'deploy-cloud-run'

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/karyakarta-agent:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/karyakarta-agent:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for entire build (20 minutes)
timeout: '1200s'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'karyakarta-agent'
