[pytest]
# Pytest Configuration for KaryaKarta Agent

# Test discovery patterns
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Test paths
testpaths = tests

# Output options
addopts =
    -v
    --strict-markers
    --tb=short
    --cov=src
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml
    --cov-branch

# Markers
markers =
    unit: Unit tests (fast, isolated)
    integration: Integration tests (may be slower)
    slow: Slow running tests

# Coverage options
[coverage:run]
source = src
omit = 
    */tests/*
    */conftest.py
    */__init__.py

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:
    @abstractmethod
